'use client'

import { useState } from 'react'
import { Copy, Download, RotateCcw, Send, Square } from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable'
import { cn } from '@/lib/utils'

const code = [`export default function GeneratedComponent() {`,`  return (`,`    <form className="flex flex-col gap-4">`,`      <h3 className="text-lg font-bold text-fg-primary">로그인</h3>`,`      <div className="flex flex-col gap-2">`,`        <label htmlFor="email" className="text-sm font-medium">이메일</label>`,`        <input id="email" type="email" autoComplete="email" placeholder="예: name@example.com" className="h-11 rounded-input border border-line-input px-3" />`,`      </div>`,`      <div className="flex flex-col gap-2">`,`        <label htmlFor="password" className="text-sm font-medium">비밀번호</label>`,`        <input id="password" type="password" autoComplete="current-password" className="h-11 rounded-input border border-line-input px-3" />`,`      </div>`,`      <label className="flex items-center gap-2 text-sm">`,`        <input type="checkbox" className="h-4 w-4 accent-brand-600" />`,`        로그인 상태 유지`,`      </label>`,`      <button type="submit" className="h-11 rounded-button bg-brand-600 font-medium text-fg-inverse">로그인</button>`,`    </form>`,`  );`,`}`]

export function Workspace({ initialState = 'done' }: { initialState?: string }) {
  const state = ['empty', 'streaming', 'done', 'fixed', 'error'].includes(initialState) ? initialState : 'done'
  const [tab, setTab] = useState<'코드'|'Diff'|'버전'>('코드')
  const [mobileTab, setMobileTab] = useState<'채팅'|'코드'|'미리보기'>('채팅')
  const [sent, setSent] = useState(false)
  const [guide, setGuide] = useState<string | null>(null)
  const fixed = state === 'fixed'
  const streaming = state === 'streaming'
  const empty = state === 'empty'
  const error = state === 'error'
  return <AppShell activeNav="워크스페이스"><div data-state={state} className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden"><div className="flex border-b border-line bg-surface lg:hidden" role="tablist" aria-label="워크스페이스 보기">{(['채팅','코드','미리보기'] as const).map((x)=><button type="button" key={x} role="tab" aria-selected={mobileTab===x} aria-controls={`mobile-panel-${x}`} onClick={()=>setMobileTab(x)} className={cn('flex-1 py-3 text-sm',mobileTab===x?'border-b-2 border-brand-600 font-medium text-fg-brand':'text-fg-secondary')}>{x}</button>)}</div><div id={`mobile-panel-${mobileTab}`} role="tabpanel" aria-label={`${mobileTab} 패널`} className="min-h-0 min-w-0 flex-1 overflow-hidden lg:hidden">{mobileTab==='채팅'?<Chat {...{empty,streaming,error,sent,setSent,guide,setGuide}}/>:mobileTab==='코드'?<Editor {...{tab,setTab,streaming}}/>:<Preview fixed={fixed}/>}</div><ResizablePanelGroup direction="horizontal" className="hidden min-h-0 min-w-0 flex-1 overflow-hidden lg:flex"><ResizablePanel defaultSize={20.3} minSize={20} className="min-w-0"><Chat {...{empty,streaming,error,sent,setSent,guide,setGuide}}/></ResizablePanel><ResizableHandle/><ResizablePanel minSize={42} className="min-w-0"><Editor {...{tab,setTab,streaming}}/></ResizablePanel><ResizableHandle/><ResizablePanel defaultSize={24.3} minSize={24} className="min-w-0"><Preview fixed={fixed}/></ResizablePanel></ResizablePanelGroup></div></AppShell>
}

function Chat({empty,streaming,error,sent,setSent,guide,setGuide}:{empty:boolean;streaming:boolean;error:boolean;sent:boolean;setSent:(v:boolean)=>void;guide:string|null;setGuide:(v:string|null)=>void}) { return <aside aria-label="채팅" className="flex h-full min-h-0 flex-col bg-surface p-4"><div className="min-h-0 flex-1 overflow-y-auto"><div className="flex flex-col gap-4 text-sm">{empty&&!sent?<p className="text-fg-muted">만들고 싶은 UI를 설명해 주세요. 적용 중인 가이드에 맞춰 코드를 만들어요.</p>:<><div className="ml-auto max-w-[90%] border border-line bg-surface p-3">로그인 폼 만들어줘</div><div className="max-w-[95%] border border-line bg-surface p-3">{streaming?'가이드에 맞춰 이메일·비밀번호 입력과 로그인 유지 체크박스가 있는 로그인 폼을 만들고 있어요.':'가이드에 맞춰 이메일·비밀번호 입력과 로그인 유지 체크박스가 있는 로그인 폼을 만들었어요. [G1][G2]'}{streaming&&<span className="ml-1 animate-pulse">▍</span>} {!streaming&&<div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span className="text-fg-muted">참고한 가이드</span><button type="button" onClick={()=>setGuide('Form > 필드 구조의 구조와 입력 요소는 수직으로 배치합니다.')} className="rounded-full border border-line px-2 py-1">[G1] Form &gt; 필드 구조</button><button type="button" onClick={()=>setGuide('Button > Variant별 스타일의 기본 버튼은 명확한 대비와 44px 높이를 사용합니다.')} className="rounded-full border border-line px-2 py-1">[G2] Button &gt; Variant별 스타일</button></div>}</div></>}{error&&<div role="alert" className="border border-line bg-surface p-3 text-danger-700">응답을 받지 못했어요. 네트워크를 확인한 뒤 다시 시도해 주세요.<Button variant="secondary" size="sm" className="mt-2" onClick={()=>setSent(false)}>다시 시도하기</Button></div>}</div></div><div className="flex flex-wrap gap-2 py-3">{['회원가입 폼','상품 카드','삭제 확인 모달'].map(x=><Button key={x} variant="ghost" size="sm" onClick={()=>setSent(true)}>{x}</Button>)}</div><form onSubmit={(e)=>{e.preventDefault();setSent(true)}} className="border-t border-line pt-3"><label htmlFor="request" className="mb-2 block text-sm font-medium">요청 입력</label><textarea id="request" placeholder="예: 이메일 입력이 있는 뉴스레터 구독 폼" className="min-h-20 w-full resize-none rounded-input border border-line-input bg-surface px-3 py-2 text-sm" /><div className="mt-2 flex items-center justify-between gap-2"><span className="text-xs text-fg-muted">Ctrl + Enter로 보내기</span><Button type="submit">{streaming?<><Square data-icon="inline-start"/>중단하기</>:<><Send data-icon="inline-start"/>보내기</>}</Button></div></form><Dialog open={!!guide} onOpenChange={(v)=>!v&&setGuide(null)}><DialogContent><DialogHeader><DialogTitle>참고한 가이드</DialogTitle></DialogHeader><p className="text-sm text-fg-secondary">{guide}</p></DialogContent></Dialog></aside> }

function Editor({tab,setTab,streaming}:{tab:'코드'|'Diff'|'버전';setTab:(x:'코드'|'Diff'|'버전')=>void;streaming:boolean}) { return <section aria-label="코드" className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden bg-surface"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-line px-4 py-2"><div role="tablist" aria-label="코드 보기" className="flex gap-1">{(['코드','Diff','버전'] as const).map(x=><button type="button" key={x} role="tab" aria-selected={tab===x} aria-controls={`editor-panel-${x}`} onClick={()=>setTab(x)} className={cn('rounded-button px-3 py-2 text-sm',tab===x?'border-b-2 border-brand-600 font-medium text-fg-brand':'text-fg-secondary')}>{x}</button>)}</div><div className="flex items-center gap-2 text-xs text-fg-secondary"><span>v3 · AI 수정</span><Button variant="ghost" size="sm"><Copy aria-hidden="true" data-icon="inline-start"/>복사하기</Button><Button variant="ghost" size="sm"><Download aria-hidden="true" data-icon="inline-start"/>다운로드하기</Button></div></div><div id={`editor-panel-${tab}`} role="tabpanel" aria-label={`${tab} 패널`} className="min-h-0 flex-1 overflow-y-auto p-4">{streaming?<pre className="max-w-full overflow-x-auto font-mono text-sm text-code-fg">{code.slice(0,8).join('\n')}</pre>:tab==='코드'?<pre className="max-w-full overflow-x-auto font-mono text-sm leading-6 text-code-fg">{code.map((line,i)=><div key={i} className={cn('flex',i===3&&!streaming?'border-l-2 border-brand-600':'')}><span className="w-8 select-none pr-3 text-right text-fg-muted">{i+1}</span><code>{line}</code></div>)}</pre>:tab==='Diff'?<div className="font-mono text-sm"><div className="border border-line p-2 text-fg-secondary">− &lt;h3 className=&quot;text-lg font-bold&quot;&gt;로그인&lt;/h3&gt;</div><div className="border border-line p-2 text-fg-secondary">+ &lt;h2 className=&quot;text-lg font-bold&quot;&gt;로그인&lt;/h2&gt;</div></div>:<div className="flex flex-col gap-3 text-sm">{['v3 · AI 수정 · 접근성 100 · 방금 전','v2 · 생성 · 접근성 92 · 2분 전','v1 · 생성 · 접근성 78 · 5분 전'].map(x=><div key={x} className="flex items-center justify-between gap-2 border-b border-line pb-3"><span>{x}</span><Button variant="secondary" size="sm"><RotateCcw aria-hidden="true" data-icon="inline-start"/>되돌리기</Button></div>)}</div>}</div></section> }

function Preview({fixed}:{fixed:boolean}) { return <section aria-label="미리보기" className="h-full min-w-0 overflow-y-auto bg-surface p-4"><h2 className="mb-3 text-base font-bold">미리보기</h2><div className="border border-line bg-surface p-4"><form className="flex flex-col gap-4"><div className="flex flex-col gap-2"><label htmlFor="preview-email" className="text-sm font-medium">이메일</label><input id="preview-email" type="email" className="h-11 rounded-input border border-line-input px-3" /></div><div className="flex flex-col gap-2"><label htmlFor="preview-password" className="text-sm font-medium">비밀번호</label><input id="preview-password" type="password" className="h-11 rounded-input border border-line-input px-3" /></div><label htmlFor="preview-remember" className="flex items-center gap-2 text-sm"><input id="preview-remember" type="checkbox" />로그인 상태 유지</label><button type="button" className="h-11 rounded-button bg-brand-600 font-medium text-fg-inverse">로그인</button></form></div><div className="mt-6 flex flex-col gap-3"><h2 className="text-base font-bold">접근성 검사</h2><p aria-live="polite" className="text-sm">접근성 점수 {fixed?'100':'92'}점 · 위반 {fixed?'0':'1'}건 · 확인 필요 1건</p>{!fixed&&<><div className="border border-line bg-surface p-3 text-sm"><span className="mr-2 rounded-full border border-line px-2 py-1 text-xs text-danger-700">심각</span>제목 단계를 건너뛰었어요 (h1 없이 h3 사용)<button type="button" className="ml-2 text-fg-brand underline">4번째 줄 보기</button></div><div className="border border-line bg-surface p-3 text-sm"><span className="mr-2 rounded-full border border-line px-2 py-1 text-xs text-warning-700">확인 필요</span>입력 필드 설명이 충분한지 확인해 주세요</div><Button className="bg-brand-600 text-fg-inverse hover:bg-brand-600">수정하기</Button><Button variant="ghost">다시 검사하기</Button></>}{fixed&&<div className="border border-line bg-surface p-3 text-sm">92점 → 100점 · 위반 1건 → 0건 · 해결: heading-order</div>}</div></section> }
